#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Khema Infrastructure Deployment     ║${NC}"
echo -e "${BLUE}║   Idempotent One-Command Setup        ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}\n"

# Check prerequisites
echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"

# Check Azure CLI
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI not found${NC}"
    exit 1
fi

# Check OpenTofu/Terraform
if command -v tofu &> /dev/null; then
    TF_CMD="tofu"
elif command -v terraform &> /dev/null; then
    TF_CMD="terraform"
else
    echo -e "${RED}Error: Neither OpenTofu nor Terraform found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Using: $TF_CMD${NC}"

# Check Azure login
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Logging in...${NC}"
    az login
fi

SUBSCRIPTION=$(az account show --query name -o tsv)
echo -e "${GREEN}✓ Azure subscription: ${SUBSCRIPTION}${NC}"

# SSH Key setup
echo -e "\n${YELLOW}[2/8] Checking SSH key...${NC}"

SSH_KEY_PATH="$HOME/.ssh/id_rsa"
if [ ! -f "$SSH_KEY_PATH" ]; then
    echo -e "${YELLOW}SSH key not found. Generating new key...${NC}"
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY_PATH" -N "" -C "khema-infra@azure"
    echo -e "${GREEN}✓ SSH key generated${NC}"
else
    echo -e "${GREEN}✓ SSH key exists${NC}"
fi

SSH_PUBLIC_KEY=$(cat "$SSH_KEY_PATH.pub")

# Check if terraform.tfvars exists
echo -e "\n${YELLOW}[3/8] Checking existing configuration...${NC}"

REUSE_CONFIG=false
if [ -f "terraform.tfvars" ]; then
    echo -e "${GREEN}✓ Found existing terraform.tfvars${NC}"
    echo -e "${BLUE}Do you want to reuse existing configuration? (yes/no)${NC}"
    read -r REUSE_ANSWER

    if [[ "$REUSE_ANSWER" == "yes" ]]; then
        REUSE_CONFIG=true
        echo -e "${GREEN}✓ Reusing existing configuration${NC}"
    else
        echo -e "${YELLOW}Creating new configuration...${NC}"
    fi
else
    echo -e "${YELLOW}No existing configuration found, creating new...${NC}"
fi

# Get or reuse credentials
echo -e "\n${YELLOW}[4/8] Setting up credentials...${NC}"

if [ "$REUSE_CONFIG" = true ]; then
    echo -e "${GREEN}✓ Using credentials from terraform.tfvars${NC}"
else
    # PostgreSQL credentials
    if [ -n "$TF_VAR_postgresql_admin_username" ] && [ -n "$TF_VAR_postgresql_admin_password" ]; then
        echo -e "${GREEN}✓ Using PostgreSQL credentials from environment${NC}"
        PG_USERNAME="$TF_VAR_postgresql_admin_username"
        PG_PASSWORD="$TF_VAR_postgresql_admin_password"
    else
        echo -e "${BLUE}PostgreSQL admin username (default: khemaadmin):${NC}"
        read -r PG_USERNAME
        PG_USERNAME=${PG_USERNAME:-khemaadmin}

        echo -e "${BLUE}PostgreSQL admin password (min 8 chars, Enter to auto-generate):${NC}"
        read -rs PG_PASSWORD
        echo

        if [ -z "$PG_PASSWORD" ]; then
            PG_PASSWORD=$(openssl rand -base64 16)
            echo -e "${GREEN}✓ Auto-generated secure password${NC}"
        fi
    fi

    # Generate secrets
    echo -e "\n${YELLOW}[5/8] Generating Langfuse secrets...${NC}"

    if [ -n "$TF_VAR_langfuse_secret_salt" ] && [ -n "$TF_VAR_nextauth_secret" ]; then
        echo -e "${GREEN}✓ Using secrets from environment${NC}"
        SALT="$TF_VAR_langfuse_secret_salt"
        NEXTAUTH="$TF_VAR_nextauth_secret"
    else
        SALT=$(openssl rand -base64 32 | tr -d '\n')
        NEXTAUTH=$(openssl rand -base64 32 | tr -d '\n')
        echo -e "${GREEN}✓ Secrets generated${NC}"
    fi

    # Create terraform.tfvars
    echo -e "\n${YELLOW}[6/8] Creating configuration file...${NC}"

    cat > terraform.tfvars <<EOF
# Auto-generated by deploy.sh on $(date)
# This file is reused on subsequent runs

location = "westeurope"

postgresql_admin_username = "$PG_USERNAME"
postgresql_admin_password = "$PG_PASSWORD"

vm_admin_username = "azureuser"

ssh_public_key = "$SSH_PUBLIC_KEY"

langfuse_secret_salt = "$SALT"
nextauth_secret      = "$NEXTAUTH"
EOF

    echo -e "${GREEN}✓ Configuration file created${NC}"

    # Save credentials
    CREDENTIALS_FILE=".credentials.txt"
    cat > "$CREDENTIALS_FILE" <<EOF
# Khema Infrastructure Credentials
# Generated: $(date)
# KEEP THIS FILE SECURE!

PostgreSQL Admin Username: $PG_USERNAME
PostgreSQL Admin Password: $PG_PASSWORD

Langfuse Secret Salt: $SALT
NextAuth Secret: $NEXTAUTH

EOF

    chmod 600 "$CREDENTIALS_FILE"
    echo -e "${GREEN}✓ Credentials saved to ${CREDENTIALS_FILE}${NC}"
fi

# Initialize Terraform
echo -e "\n${YELLOW}[7/8] Initializing Terraform...${NC}"
$TF_CMD init -upgrade

# Validate
$TF_CMD validate > /dev/null
echo -e "${GREEN}✓ Configuration valid${NC}"

# Plan
echo -e "\n${YELLOW}[8/8] Checking for infrastructure changes...${NC}"
$TF_CMD plan -detailed-exitcode -out=tfplan 2>/dev/null || PLAN_EXIT=$?

# Exit codes: 0 = no changes, 1 = error, 2 = changes present
if [ "${PLAN_EXIT:-0}" -eq 0 ]; then
    echo -e "${GREEN}✓ Infrastructure is up-to-date, no changes needed${NC}"
    rm -f tfplan

    echo -e "\n${BLUE}Showing current deployment:${NC}"
    $TF_CMD output 2>/dev/null || echo "No infrastructure deployed yet"

    exit 0
elif [ "${PLAN_EXIT:-0}" -eq 2 ]; then
    echo -e "${YELLOW}Changes detected:${NC}\n"

    # Show summary
    $TF_CMD show tfplan | head -50

    echo -e "\n${BLUE}Full plan saved to tfplan${NC}"
    echo -e "${YELLOW}Do you want to apply these changes? (yes/no)${NC}"
    read -r CONFIRM

    if [[ "$CONFIRM" != "yes" ]]; then
        echo -e "${YELLOW}Deployment cancelled${NC}"
        rm -f tfplan
        exit 0
    fi

    echo -e "\n${GREEN}Applying changes...${NC}"
    $TF_CMD apply tfplan
    rm -f tfplan

    # Show results
    echo -e "\n${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║   Deployment Complete! 🚀              ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════╝${NC}\n"

    $TF_CMD output

    echo -e "\n${YELLOW}⏳ If this is first deployment, wait 2-3 minutes for Docker services to start${NC}"
    echo -e "${GREEN}Credentials saved in: .credentials.txt${NC}\n"

else
    echo -e "${RED}Error during terraform plan${NC}"
    rm -f tfplan
    exit 1
fi
