#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Khema Infrastructure Deployment     ║${NC}"
echo -e "${BLUE}║   Fully Automated - Zero Input         ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}\n"

# Check prerequisites
echo -e "${YELLOW}[1/7] Checking prerequisites...${NC}"

# Check Azure CLI
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI not found${NC}"
    exit 1
fi

# Check OpenTofu/Terraform
if command -v tofu &> /dev/null; then
    TF_CMD="tofu"
elif command -v terraform &> /dev/null; then
    TF_CMD="terraform"
else
    echo -e "${RED}Error: Neither OpenTofu nor Terraform found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Using: $TF_CMD${NC}"

# Check Azure login
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Logging in...${NC}"
    az login
fi

SUBSCRIPTION=$(az account show --query name -o tsv)
echo -e "${GREEN}✓ Azure subscription: ${SUBSCRIPTION}${NC}"

# SSH Key setup
echo -e "\n${YELLOW}[2/7] Setting up SSH key...${NC}"

SSH_KEY_PATH="$HOME/.ssh/id_rsa"
if [ ! -f "$SSH_KEY_PATH" ]; then
    echo -e "${YELLOW}Generating SSH key...${NC}"
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY_PATH" -N "" -C "khema-infra@azure"
    echo -e "${GREEN}✓ SSH key generated${NC}"
else
    echo -e "${GREEN}✓ SSH key exists${NC}"
fi

SSH_PUBLIC_KEY=$(cat "$SSH_KEY_PATH.pub")

# Check for existing configuration
echo -e "\n${YELLOW}[3/7] Checking configuration...${NC}"

if [ -f "terraform.tfvars" ]; then
    echo -e "${GREEN}✓ Found existing terraform.tfvars - reusing configuration${NC}"
    REUSE_CONFIG=true
else
    echo -e "${YELLOW}Creating new configuration...${NC}"
    REUSE_CONFIG=false
fi

# Generate or reuse credentials
echo -e "\n${YELLOW}[4/7] Setting up credentials...${NC}"

if [ "$REUSE_CONFIG" = true ]; then
    echo -e "${GREEN}✓ Using existing configuration${NC}"
else
    # Auto-generate PostgreSQL credentials
    if [ -n "$TF_VAR_postgresql_admin_username" ] && [ -n "$TF_VAR_postgresql_admin_password" ]; then
        echo -e "${GREEN}✓ Using PostgreSQL credentials from environment${NC}"
        PG_USERNAME="$TF_VAR_postgresql_admin_username"
        PG_PASSWORD="$TF_VAR_postgresql_admin_password"
    else
        # Generate secure random username (hard to guess)
        PG_USERNAME="pgadmin_$(openssl rand -hex 4)"
        PG_PASSWORD=$(openssl rand -base64 24)
        echo -e "${GREEN}✓ Auto-generated PostgreSQL credentials${NC}"
    fi

    # Generate secrets
    echo -e "\n${YELLOW}[5/7] Generating secrets...${NC}"

    if [ -n "$TF_VAR_langfuse_secret_salt" ] && [ -n "$TF_VAR_nextauth_secret" ] && [ -n "$TF_VAR_encryption_key" ]; then
        echo -e "${GREEN}✓ Using secrets from environment${NC}"
        SALT="$TF_VAR_langfuse_secret_salt"
        NEXTAUTH="$TF_VAR_nextauth_secret"
        ENCRYPTION_KEY="$TF_VAR_encryption_key"
    else
        SALT=$(openssl rand -base64 32 | tr -d '\n')
        NEXTAUTH=$(openssl rand -base64 32 | tr -d '\n')
        ENCRYPTION_KEY=$(openssl rand -hex 32)  # 64 hex chars = 256 bits
        echo -e "${GREEN}✓ All secrets generated${NC}"
    fi

    # Create terraform.tfvars
    echo -e "\n${YELLOW}[6/7] Creating configuration file...${NC}"

    cat > terraform.tfvars <<EOF
# Auto-generated by deploy.sh on $(date)
# This file is reused on subsequent runs
# All credentials are auto-generated for maximum security

location = "westeurope"

# PostgreSQL Credentials (auto-generated)
postgresql_admin_username = "$PG_USERNAME"
postgresql_admin_password = "$PG_PASSWORD"

# VM Configuration
vm_admin_username = "azureuser"

# SSH Public Key
ssh_public_key = "$SSH_PUBLIC_KEY"

# Langfuse Secrets (auto-generated)
langfuse_secret_salt = "$SALT"
nextauth_secret      = "$NEXTAUTH"
encryption_key       = "$ENCRYPTION_KEY"
EOF

    echo -e "${GREEN}✓ Configuration file created${NC}"

    # Save credentials backup
    CREDENTIALS_FILE=".credentials.txt"
    cat > "$CREDENTIALS_FILE" <<EOF
# Khema Infrastructure Credentials
# Generated: $(date)
# KEEP THIS FILE SECURE!

PostgreSQL:
  Username: $PG_USERNAME
  Password: $PG_PASSWORD

Langfuse Secrets:
  Salt: $SALT
  NextAuth Secret: $NEXTAUTH
  Encryption Key: $ENCRYPTION_KEY

SSH Key: $SSH_KEY_PATH
EOF

    chmod 600 "$CREDENTIALS_FILE"
    echo -e "${GREEN}✓ Credentials backed up to ${CREDENTIALS_FILE}${NC}"
fi

# Initialize and validate
echo -e "\n${YELLOW}[7/7] Deploying infrastructure...${NC}"
$TF_CMD init -upgrade > /dev/null
$TF_CMD validate > /dev/null
echo -e "${GREEN}✓ Configuration valid${NC}"

# Plan and check for changes
$TF_CMD plan -detailed-exitcode -out=tfplan 2>/dev/null || PLAN_EXIT=$?

if [ "${PLAN_EXIT:-0}" -eq 0 ]; then
    echo -e "${GREEN}✓ Infrastructure is up-to-date${NC}\n"
    rm -f tfplan

    echo -e "${BLUE}Current deployment:${NC}"
    $TF_CMD output 2>/dev/null || echo "No infrastructure deployed yet"

    exit 0
elif [ "${PLAN_EXIT:-0}" -eq 2 ]; then
    echo -e "${YELLOW}Changes detected - applying automatically...${NC}\n"

    $TF_CMD apply -auto-approve tfplan
    rm -f tfplan

    echo -e "\n${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║   Deployment Complete! 🚀              ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════╝${NC}\n"

    $TF_CMD output

    if [ "$REUSE_CONFIG" = false ]; then
        echo -e "\n${BLUE}📝 Important:${NC}"
        echo -e "${GREEN}Credentials saved in: ${CREDENTIALS_FILE}${NC}"
        echo -e "${YELLOW}⏳ Wait 2-3 minutes for Docker services to start${NC}\n"
    fi
else
    echo -e "${RED}Error during terraform plan${NC}"
    rm -f tfplan
    exit 1
fi
